version: "3.5"
services:
  mongo-express:
    image: mongo-express
    networks:
      artcoded:
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    ports:
      - 8081:8081
  keycloak:
    # image: nbittich/keycloak:latest
    environment:
      KC_HOSTNAME_ADMIN_URL: https://auth.somehost.org
      KC_HOSTNAME_URL: https://auth.somehost.org
      KC_HOSTNAME_STRICT_HTTPS: "no"
      KC_HTTP_ENABLED: "yes"
    user:
      root
      #ports:
      #- 8080:8080
    networks:
      artcoded:
        aliases:
          - auth.somehost.org
    volumes:
      - ./config/keycloak-dev/export:/tmp/export
      - ./config/keycloak-dev/import:/tmp/import
      # - ./config/keycloak-dev:/tmp/realms
  api-backend:
    image:
      nbittich/api-backend:latest
      #  ports:
      # - 9000:80
    links:
      - greenmail
    networks:
      artcoded:
        aliases:
          - api.somehost.org
    environment:
      CAMEL_MAIL_IMAP_USERNAME: "fee@somehost.com"
      CAMEL_MAIL_IMAP_PASSWORD: "fee"
      CAMEL_MAIL_IMAP_SSL: "false"
      CAMEL_MAIL_IMAP_HOST: "greenmail.somehost.org"
      CAMEL_MAIL_IMAP_PROTOCOL: imap
      CAMEL_MAIL_IMAP_PORT: 143
      MAIL_SENDER_USERNAME: "noreply@somehost.com"
      MAIL_SENDER_PASSWORD: "noreply"
      MAIL_SENDER_SERVER: "greenmail.somehost.org"
      MAILE_SENDER_SSL_ENABLE: "false"
      MAIL_SENDER_PORT: 25
      MONGO_DB_DATABASE_NAME: artcoded_test
      JWK_SET_URI: http://auth.somehost.org:8080/realms/Artcoded/protocol/openid-connect/certs
      MAIL_SEARCH_TERM: /usr/config/dev/search-term.yml
  back-office:
    image: nbittich/back-office:latest
    networks:
      artcoded:
        aliases:
          - backoffice.somehost.org
    environment:
      KEYCLOAK_URL: "https://auth.somehost.org"
      KEYCLOAK_REALM: "Artcoded"
      KEYCLOAK_CLIENT_ID: "frontend-client"
      BACKEND_URL: "https://backoffice.somehost.org"
      SPARQL_ENDPOINT: "https://backoffice.somehost.org/sparql"
      FRONTEND_URL: "https://somehost.org"
  website:
    image: nbittich/websitev2:latest
    networks:
      artcoded:
        aliases:
          - somehost.org
    environment:
      BACKEND_URL: "http://api-backend"
      SERVER_PORT: 80
      SPARQL_DEFAULT_URL: "http://triplestore/public/sparql"
  mongo:
    ports:
      - 27018:27017
  artemis:
    volumes:
      - ./config/artemis/keycloak_dev.json:/var/lib/artemis-instance/etc/keycloak.json
    ports:
      - 8161:8161
      - 61616:61616
  redis:
    ports:
      - "6379:6379"
  api-gateway:
    image:
      nbittich/api-gateway:latest
      #ports:
      #- "80:80"
    environment:
      GATEWAY_CONFIG_FILE: /usr/config/gateway-dev.yml
  tlsproxy:
    restart: "always"
    build:
      context: ./nginx-dev/.
    networks:
      artcoded:
    ports:
      - "443:443"
      - "8883:8883"
    volumes:
      - ./config/tlsproxy/http:/etc/nginx/conf.d
      - ./config/tlsproxy/tcp:/etc/nginx/tcpconf.d
      - ./config/tlsproxy/nginx.conf:/etc/nginx/nginx.conf

  triplestore:
    image:
      nbittich/triplestore:latest
      #ports:
      #- 8888:80
  prometheus:
    user: root
    restart: "no"
    volumes:
      - ./config/prometheus/prometheus_dev.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    user: root
    restart: "no"
    ports:
      - 3000:3000
  greenmail:
    image: greenmail/standalone:1.6.7
    restart: always
    networks:
      artcoded:
        aliases:
          - greenmail.somehost.org
    environment:
      GREENMAIL_OPTS: "-Dgreenmail.hostname=0.0.0.0 -Dgreenmail.users.login=email -Dgreenmail.setup.all -Dgreenmail.users=fee:fee@somehost.com,noreply:noreply@somehost.com,accountant1:accountant1@somehost.com,accountant2:accountant2@somehost.com"
    ports:
      - "8996:8080"
  roundcube:
    image: roundcube/roundcubemail:latest
    depends_on:
      - greenmail
    networks:
      artcoded:
        aliases:
          - mail.somehost.org
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: greenmail
      ROUNDCUBEMAIL_DEFAULT_PORT: 143
      ROUNDCUBEMAIL_SMTP_SERVER: greenmail
      ROUNDCUBEMAIL_SMTP_PORT: 25
networks:
  artcoded:
