version: '3.5'
services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: __MONGO_INITDB_ROOT_USERNAME__
      MONGO_INITDB_ROOT_PASSWORD: __MONGO_INITDB_ROOT_PASSWORD__
  mongo-express:
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: __MONGO_INITDB_ROOT_USERNAME__
      ME_CONFIG_MONGODB_AUTH_PASSWORD: __MONGO_INITDB_ROOT_PASSWORD__
      ME_CONFIG_MONGODB_URL: mongodb://__MONGO_INITDB_ROOT_USERNAME__:__MONGO_INITDB_ROOT_PASSWORD__@mongo:27017/
  api-backend:
    networks:
      artcoded:
        aliases:
          - api.bittich.be
    environment:
      CAMEL_MAIL_IMAP_USERNAME: __CAMEL_MAIL_IMAP_USERNAME__
      CAMEL_MAIL_IMAP_PASSWORD: __CAMEL_MAIL_IMAP_PASSWORD__
      MAIL_SENDER_USERNAME: __MAIL_SENDER_USERNAME__
      MAIL_SENDER_PASSWORD: __MAIL_SENDER_PASSWORD__
      MONGO_DB_DATABASE_NAME: "artcoded"
      MONGO_DB_PASSWORD: __MONGO_INITDB_ROOT_PASSWORD__
      MONGO_DB_USERNAME: __MONGO_INITDB_ROOT_USERNAME__
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: __ARTEMIS_PASSWORD__
      JWK_SET_URI: http://keycloak:8080/realms/Artcoded/protocol/openid-connect/certs
      MAIL_SEARCH_TERMS: __MAIL_SEARCH_TERMS__

  back-office:
    networks:
      artcoded:
        aliases:
          - backoffice.bittich.be
    environment:
      KEYCLOAK_URL: "https://auth.bittich.be"
      KEYCLOAK_REALM: "Artcoded"
      KEYCLOAK_CLIENT_ID: "frontend-client"
      SPARQL_ENDPOINT: "https://backoffice.bittich.be/sparql"
      BACKEND_URL: "https://backoffice.bittich.be"
      FRONTEND_URL: "https://bittich.be"
      ENV_TYPE: "PROD"

  website:
    networks:
      artcoded:
        aliases:
          - bittich.be
    environment:
      BACKEND_URL: "https://bittich.be"
      SERVER_BACKEND_URL: "http://bittich.be"
      SPARQL_ENDPOINT: "https://bittich.be/sparql"
      ENV_TYPE: "PROD"
  api-gateway:
    environment:
      GATEWAY_CONFIG_FILE: /usr/config/gateway_prod.yml
  postgresql:
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
      POSTGRES_DB: keycloak
  keycloak: 
    networks:
      artcoded:
        aliases:
          - auth.bittich.be
    environment:  
      KC_DB_PASSWORD: __POSTGRES_PASSWORD__
      KC_HOSTNAME: __KEYCLOAK_HOSTNAME__
      # user: root
      
  artemis:
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: __ARTEMIS_PASSWORD__
  mongo-dump-sync:
    image: nbittich/drive-sync:2022.1.0
    networks:
      artcoded:
    volumes:
      - openj9cache:/opt/shareclasses
      - ./data/backend/dump:/var/artcoded/data
      - ./data/mongo-dump-sync:/var/drive-sync/
      - ./config/drive-sync:/usr/config
    environment:
      PATH_TO_SYNC: /var/artcoded/data
      IDEM_POTENT_FILE_PATH: /var/drive-sync/idempot.dat
      DRIVE_CREDENTIALS_FILE: /usr/config/artcoded-cred.json
      DRIVE_SHARED_DIRECTORY: "v2022.openartcoded-mongo-dump"
      APPLICATION_NAME: __DRIVE_APPLICATION_NAME__
      ARTEMIS_USER: artemis
      ARTEMIS_URL: tcp://artemis:61616
      ARTEMIS_PASSWORD: __ARTEMIS_PASSWORD__
  dossiers-dump-sync:
    image: nbittich/drive-sync:2022.1.0
    networks:
      artcoded:
    volumes:
      - openj9cache:/opt/shareclasses
      - ./data/backend/dossiers-backup:/var/artcoded/data
      - ./data/dossiers-dump-sync:/var/drive-sync/
      - ./config/drive-sync:/usr/config
    environment:
      PATH_TO_SYNC: /var/artcoded/data
      IDEM_POTENT_FILE_PATH: /var/drive-sync/idempot.dat
      DRIVE_CREDENTIALS_FILE: /usr/config/artcoded-cred.json
      DRIVE_SHARED_DIRECTORY: "v2022.openartcoded-compta-2022"
      APPLICATION_NAME: __DRIVE_APPLICATION_NAME__
      ARTEMIS_USER: artemis
      ARTEMIS_URL: tcp://artemis:61616
      ARTEMIS_PASSWORD: __ARTEMIS_PASSWORD__

  ####### Triplestore #######
  triplestore:
    environment:
      UNION_DEFAULT_GRAPH: "true"     
      SECONDS_BEFORE_QUERY_TIMEOUT: "40"
      BANDWIDTH_CAPACITY: "30"
      ARTEMIS_USER: artemis
      ARTEMIS_URL: tcp://artemis:61616
      ARTEMIS_PASSWORD: __ARTEMIS_PASSWORD__
      JWK_SET_URI: http://keycloak:8080/realms/Artcoded/protocol/openid-connect/certs
  grafana:
    restart: unless-stopped
    user: "1000"
    ports:
      - 3000:3000
  prometheus:
    user: "1000"
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus_prod.yml:/etc/prometheus/prometheus.yml

# Mail
  roundcube:
    image: roundcube/roundcubemail:latest
    networks:
      artcoded:
        aliases:
          - cube.bittich.be
    environment:
        ROUNDCUBEMAIL_DEFAULT_HOST: SSL0.OVH.NET
        ROUNDCUBEMAIL_DEFAULT_PORT: 993
        ROUNDCUBEMAIL_SMTP_SERVER: SSL0.OVH.NET
        ROUNDCUBEMAIL_SMTP_PORT: 465 
networks:
  artcoded: 
    external:
      name: custom_network
