
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
scrape_configs:
  - job_name: 'api-backend'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['api-backend:80']
    oauth2:
      client_id: 'prometheus'
      client_secret: 'U03e8p3LXIbV4VJPopEUbN55cjGAm3oE'
      token_url: http://keycloak:8080/realms/Artcoded/protocol/openid-connect/token
  - job_name: 'triplestore'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['triplestore:80']
    oauth2:
      client_id: 'prometheus'
      client_secret: 'U03e8p3LXIbV4VJPopEUbN55cjGAm3oE'
      token_url: http://keycloak:8080/realms/Artcoded/protocol/openid-connect/token